// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuKTP6OydP2JI8308mlmowSeXLOtELO_k',
    appId: '1:87094572973:web:060431f052014293239324',
    messagingSenderId: '87094572973',
    projectId: 'note-app-9a667',
    authDomain: 'note-app-9a667.firebaseapp.com',
    storageBucket: 'note-app-9a667.appspot.com',
    measurementId: 'G-JPJH2RG3XW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBrX7zGpJ2gcfZakj9Gn7ZOHy7ZvMybOw',
    appId: '1:87094572973:android:645c7af65f68c97c239324',
    messagingSenderId: '87094572973',
    projectId: 'note-app-9a667',
    storageBucket: 'note-app-9a667.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdK5hyLd6UyDkfN6HvsID8h4OKW0ag1Qg',
    appId: '1:87094572973:ios:a6e98459d04ce433239324',
    messagingSenderId: '87094572973',
    projectId: 'note-app-9a667',
    storageBucket: 'note-app-9a667.appspot.com',
    iosClientId: '87094572973-3l2g3r6mhctqd36vnutns9m229q0te5f.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdK5hyLd6UyDkfN6HvsID8h4OKW0ag1Qg',
    appId: '1:87094572973:ios:a6e98459d04ce433239324',
    messagingSenderId: '87094572973',
    projectId: 'note-app-9a667',
    storageBucket: 'note-app-9a667.appspot.com',
    iosClientId: '87094572973-3l2g3r6mhctqd36vnutns9m229q0te5f.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );
}
